import type { EngineManifestExport } from "./worldDocumentEngineExports";
import type { WorldMapExportPackage } from "./worldDocumentMapExports";

export function createEngineHandoffReadme(
  packageDraft: WorldMapExportPackage,
  engineManifest: EngineManifestExport,
) {
  const lines = [
    `# ${packageDraft.manifest.name} AGM Engine Package`,
    "",
    `Profile: ${packageDraft.manifest.profileLabel}`,
    `Seed: ${packageDraft.map.seed}`,
    `Map size: ${packageDraft.map.width} x ${packageDraft.map.height}`,
    "",
    "## What this package is / 这个包是什么",
    "",
    "AGM Engine Package is a handoff bundle for game teams that need structured map, terrain, and importer sample data.",
    "AGM Engine Package 是面向游戏团队交接的导出包，包含结构化地图、地形与导入器源码示例数据。",
    "It is designed for export, extraction, local validation, and engine-side adaptation.",
    "它用于导出、解压、本地校验，以及在引擎侧继续改造导入流程。",
    "",
    "## Current contract / 当前契约",
    "",
    `- schema: ${engineManifest.artifactContract.schema}`,
    `- packageFormat: ${engineManifest.artifactContract.packageFormat}`,
    `- layoutVersion: ${engineManifest.artifactContract.layoutVersion}`,
    `- validationMode: ${engineManifest.artifactContract.validationMode}`,
    `- zipParsingSupported: ${engineManifest.artifactContract.zipParsingSupported}`,
    `- productionPluginsIncluded: ${engineManifest.artifactContract.productionPluginsIncluded}`,
    "",
    "## Quick handoff / 快速交接",
    "",
    "1. Export Engine Package ZIP from AGM Studio.",
    "2. Extract the ZIP to a local folder.",
    "3. Run `npm run validate:unity-export -- --dir <extracted-package-root>`.",
    "4. Optionally pass `--unity <Unity executable>` or set `UNITY_EXECUTABLE` for Unity CLI validation.",
    "5. Adapt source samples under `handoff/importers/` for your engine project.",
    "",
    "1. 从 AGM Studio 导出 Engine Package ZIP。",
    "2. 将 ZIP 解压到本地目录。",
    "3. 运行 `npm run validate:unity-export -- --dir <解压后的包目录>`。",
    "4. 可选传入 `--unity <Unity executable>` 或设置 `UNITY_EXECUTABLE` 执行 Unity CLI 校验。",
    "5. 基于 `handoff/importers/` 下的源码示例改造你的引擎项目导入器。",
    "",
    "## Package entry points / 包入口",
    "",
    ...engineManifest.importerHandoff.entryFiles.map(
      (file) => `- ${file.kind}: ${file.path}`,
    ),
    `- importer-sample-metadata: ${engineManifest.importerHandoff.sampleMetadataPath}`,
    "",
    "## Importer status / 导入器状态",
    "",
    "This package includes handoff metadata and sample import settings for engine-side scripts.",
    "此包包含用于引擎侧脚本的交接 metadata 与示例导入设置。",
    `Artifact contract: ${engineManifest.artifactContract.schema} / ${engineManifest.artifactContract.packageFormat} layout v${engineManifest.artifactContract.layoutVersion}.`,
    `Validation mode: ${engineManifest.artifactContract.validationMode}; direct --zip validation is reserved and not implemented by the local harness yet.`,
    "It includes source samples only; no production plugin, Unity package, Godot addon, or Unreal plugin is included.",
    "当前仅包含源码示例；不包含生产级插件、Unity package、Godot addon 或 Unreal plugin。",
    "",
    "## Sample importer stubs",
    "",
    "These files are minimal samples and starting points, not full plugins or editor extensions.",
    ...engineManifest.importerHandoff.sampleStubPaths.flatMap((stub) => [
      `### ${stub.engine}`,
      ...stub.paths.map((path) => `- ${path}`),
      "",
    ]),
    "## Unity source importer spike",
    "",
    "Unity source importer spike files are included as source samples only.",
    "Unity-first vertical slice prototype reads package-layout, importer metadata, terrain RAW16/heightfield, and resource/province/biome map layers.",
    "It emits metadata-only terrain/map-layer importer reports and keeps the exported ZIP free of Unity assets, packages, compiled plugins, or production plugins.",
    "Unity importer asset authoring source sample can create temporary TerrainData, ScriptableObject, and prefab prototype assets only inside the validator Unity project at Assets/AGM/Validation/EditorPrototypeAssets/.",
    "Unity-first vertical slice prototype 会读取 package-layout、importer metadata、terrain RAW16/heightfield，以及 resource/province/biome 地图层。",
    "它会输出 metadata-only terrain/map-layer importer report，并保持导出的 ZIP 不包含 Unity assets、packages、compiled plugins 或生产级插件。",
    "Unity importer asset authoring 源码示例只会在 validator Unity project 的 Assets/AGM/Validation/EditorPrototypeAssets/ 下创建临时 TerrainData、ScriptableObject 与 prefab prototype assets。",
    "They are not runtime-validated by AGM CI, and no Unity project, package, or plugin is bundled.",
    ...engineManifest.importerHandoff.unityImporterArtifactPaths.map(
      (path) => `- ${path}`,
    ),
    "",
    "## Validation / 校验",
    "",
    `Local validation script: ${engineManifest.importerHandoff.unityValidationHarness.scriptPath}`,
    "Run `npm run validate:unity-export -- --dir <extracted-package-root>` against an extracted package directory to validate manifest JSON, importer metadata, artifact contract, Unity source-sample layout, RAW16 byte length, little-endian RAW16 decoding, terrain prototype metadata, and map layer JSON files.",
    "请对已解压的包目录运行 `npm run validate:unity-export -- --dir <解压后的包目录>`，用于校验 manifest JSON、importer metadata、artifact contract、Unity 源码示例 layout、RAW16 byte length、little-endian RAW16 解码、terrain prototype metadata 与地图层 JSON。",
    "Direct `--zip` validation is reserved and not implemented yet; extract the ZIP first and validate with `--dir`.",
    "直接 `--zip` 校验仍是预留能力，尚未实现；请先解压 ZIP，再用 `--dir` 校验。",
    `If Unity CLI is supplied with --unity or UNITY_EXECUTABLE, the harness creates a temporary Unity project, copies the source samples, runs ${engineManifest.importerHandoff.unityValidationHarness.batchmodeMethod}, calls ${engineManifest.importerHandoff.unityValidationHarness.importerSmokeTest}, and writes ${engineManifest.importerHandoff.unityValidationHarness.prototypeReport} with ${engineManifest.importerHandoff.unityValidationHarness.terrainPrototypeReport} metadata plus validator-scoped editor prototype assets under Assets/AGM/Validation/EditorPrototypeAssets/.`,
    "If Unity CLI is not supplied, the harness reports structure validation only; editor prototype assets are not created outside the temporary Unity validation project.",
    "如果未提供 Unity CLI，harness 只报告结构校验；editor prototype assets 不会在临时 Unity 校验项目之外创建。",
    "",
    "## Terrain data",
    "",
    `RAW16 encoding: ${engineManifest.terrainSource.rawEncoding}`,
    `RAW16 range: ${engineManifest.terrainSource.rawRange.min}..${engineManifest.terrainSource.rawRange.max}`,
    `Heightfield normalized range: ${engineManifest.terrainSource.normalizedRange.min}..${engineManifest.terrainSource.normalizedRange.max}`,
    `Coordinate system: ${engineManifest.terrainSource.coordinateSystem}`,
    "",
    "## Engine package structures",
    "",
    ...engineManifest.enginePackageStructure.flatMap((packageStructure) => [
      `### ${packageStructure.engine}`,
      `Root: ${packageStructure.root}`,
      `Directories: ${packageStructure.directories.join(", ")}`,
      `Importer: ${packageStructure.importHints.importer}`,
      `Terrain files: ${packageStructure.terrainFiles.map((file) => `${file.kind} -> ${file.recommendedPath}`).join("; ")}`,
      "Import steps: copy the package under the recommended root, read the engine manifest, load RAW16 using the terrain settings, then consume resource/province/biome maps as gameplay layers.",
      "",
    ]),
    "## Required package files",
    "",
    ...engineManifest.importerHandoff.layout.requiredFiles.map(
      (path) => `- ${path}`,
    ),
    "",
    "## Optional package files",
    "",
    ...engineManifest.importerHandoff.layout.optionalFiles.map(
      (path) => `- ${path}`,
    ),
    "",
  ];

  return lines.join("\n");
}
