export function createUnityProductionImporterPackagingPlan(
  unityImporterArtifactPaths: string[],
) {
  return {
    status: "scaffolded-separate-deliverable",
    scaffoldStatus: "runtime-importer-contract-hardened",
    packageName: "com.agm.importers.unity",
    packageRoot: "Packages/com.agm.importers.unity",
    distribution: "separate-versioned-unity-package",
    packageVersion: "0.1.0-preview.1",
    includedInEnginePackageZip: false,
    requiresProductionizationReview: true,
    packageJsonIncludedInEnginePackage: false,
    asmdefIncludedInEnginePackage: false,
    compiledAssembliesIncludedInEnginePackage: false,
    runtimeAssembly: "AGM.Importers.Unity.Runtime",
    editorAssembly: "AGM.Importers.Unity.Editor",
    plannedFiles: [
      "package.json",
      "Runtime/AGM.Importers.Unity.Runtime.asmdef",
      "Runtime/AgmRuntimePackageImporter.cs",
      "Runtime/AgmPackageTypes.cs",
      "Editor/AGM.Importers.Unity.Editor.asmdef",
      "Editor/AgmImportMenu.cs",
      "Editor/AgmImporterWindow.cs",
      "Editor/AgmAssetAuthoringPrototype.cs",
      "Samples~/ImporterFixture/README.md",
      "README.md",
    ],
    scaffoldFiles: [
      "package.json",
      "Runtime/AGM.Importers.Unity.Runtime.asmdef",
      "Runtime/AgmRuntimePackageImporter.cs",
      "Runtime/AgmPackageTypes.cs",
      "Editor/AGM.Importers.Unity.Editor.asmdef",
      "Editor/AgmImportMenu.cs",
      "Editor/AgmImporterWindow.cs",
      "Editor/AgmAssetAuthoringPrototype.cs",
      "Samples~/ImporterFixture/README.md",
      "README.md",
    ],
    scaffoldValidation:
      "local-repository-package-files-and-runtime-importer-contract",
    runtimeImporterContract: {
      status: "reads-engine-package-contract",
      readsManifest: true,
      readsPackageLayout: true,
      readsSampleMetadata: true,
      readsHeightfieldJson: true,
      readsRaw16Terrain: true,
      readsMapLayers: ["resource", "province", "biome"],
      validatesRaw16ByteLength: true,
      validatesHeightfieldGrid: true,
      countsMapLayerRecords: true,
      exposesInspectReport: true,
      inspectReportSchema: "agm.unity-runtime-import-report.v0",
      exposesImportSummary: true,
      exposesIssueTaxonomy: true,
      issueSchema: "agm.unity-runtime-import-issue.v0",
      issueCodes: [
        "package-root-missing",
        "required-directory-missing",
        "required-file-count-mismatch",
        "heightfield-grid-missing",
        "heightfield-sample-count-mismatch",
        "raw16-byte-length-mismatch",
      ],
      usageContract: {
        packageInstallMode: "separate-unity-package",
        importApi:
          "AGM.Importers.Unity.AgmRuntimePackageImporter.ImportFromUnpackedPackage",
        inspectApi:
          "AGM.Importers.Unity.AgmRuntimePackageImporter.InspectUnpackedPackage",
        errorContract: "AgmImportException.Issue",
        runtimeCreatesAssets: false,
      },
      productionAssetOutput: false,
    },
    releaseCandidateReview: {
      status: "pre-release-candidate-checklist",
      packageMetadataReviewed: true,
      usageContractDocumented: true,
      runtimeIssueTaxonomyCovered: true,
      mockUnityFixtureRequired: true,
      realUnityValidationRequired: true,
      enginePackageZipBoundaryRequired: true,
      releaseCandidateReady: false,
    },
    packageCompileGate: {
      status: "validator-temp-unity-project-compile-gate",
      packageCopiedToTempProject: true,
      packageRoot: "Packages/com.agm.importers.unity",
      validatesPackageJson: true,
      validatesRuntimeAsmdef: true,
      validatesEditorAsmdef: true,
      validatesRuntimeImporterSource: true,
      validatesEditorSource: true,
      includedInEnginePackageZip: false,
    },
    packageImportSmokeTest: {
      schema: "agm.unity-package-import-smoke-test.v0",
      status: "validator-temp-unity-project-package-importer-smoke-test",
      packageImporter:
        "AGM.Importers.Unity.AgmRuntimePackageImporter.ImportFromUnpackedPackage",
      sourceSampleImporter:
        "AgmRuntimePackageImporter.ImportFromUnpackedPackage",
      runtimeApi:
        "AGM.Importers.Unity.AgmRuntimePackageImporter.InspectUnpackedPackage",
      runtimeReportSchema: "agm.unity-runtime-import-report.v0",
      comparesAgainstSourceSample: true,
      validatesPackageId: true,
      validatesTerrainGrid: true,
      validatesRaw16Terrain: true,
      validatesMapLayerRecords: true,
      productionAssetOutput: false,
      includedInEnginePackageZip: false,
    },
    validationGates: [
      "artifact-contract",
      "package-layout",
      "raw16-terrain-import",
      "map-layer-import",
      "editor-asset-authoring",
      "unity-package-import-smoke-test",
      "unity-package-release-candidate-review",
      "no-export-zip-plugin-contamination",
    ],
    sourceSampleInputs: unityImporterArtifactPaths,
    enginePackageBoundaryRef: "productionPluginBoundary",
  };
}
