import type {
  ImporterStubContext,
  ImporterStubFile,
} from "./worldDocumentImporterStubTypes";

export function createUnityRuntimePackageImporterFile({
  baseName,
  manifestPath,
  packageDraft,
  raw16Path,
  sampleMetadataPath,
}: ImporterStubContext): ImporterStubFile {
  return {
    path: "handoff/importers/unity/Runtime/AgmRuntimePackageImporter.cs.txt",
    content: [
      "using System;",
      "using System.IO;",
      "using System.Text;",
      "using UnityEngine;",
      "",
      "public static class AgmRuntimePackageImporter",
      "{",
      "    public static AgmImportedPackage ImportFromUnpackedPackage(string packageRoot)",
      "    {",
      '        if (string.IsNullOrWhiteSpace(packageRoot)) ThrowImportIssue(AgmImportIssueCode.PackageRootMissing, "Package root is required.", string.Empty, "non-empty path", "empty");',
      '        if (!Directory.Exists(packageRoot)) ThrowImportIssue(AgmImportIssueCode.PackageRootMissing, $"Package root does not exist: {packageRoot}", packageRoot, "existing directory", "missing");',
      `        var manifestJson = File.ReadAllText(Path.Combine(packageRoot, "${manifestPath}"));`,
      `        var packageLayoutJson = File.ReadAllText(Path.Combine(packageRoot, "handoff/importers/unity/package-layout.json"));`,
      `        var sampleMetadataJson = File.ReadAllText(Path.Combine(packageRoot, "${sampleMetadataPath}"));`,
      `        var heightfieldJson = File.ReadAllText(Path.Combine(packageRoot, "terrain/${baseName}.agm-heightfield.json"));`,
      `        var resourceMapJson = File.ReadAllText(Path.Combine(packageRoot, "maps/${baseName}.agm-resource-map.json"));`,
      `        var provinceMapJson = File.ReadAllText(Path.Combine(packageRoot, "maps/${baseName}.agm-province-map.json"));`,
      `        var biomeMapJson = File.ReadAllText(Path.Combine(packageRoot, "maps/${baseName}.agm-biome-map.json"));`,
      `        var rawBytes = File.ReadAllBytes(Path.Combine(packageRoot, "${raw16Path}"));`,
      "        var heightfieldSampleCount = CountHeightfieldValues(heightfieldJson);",
      `        var gridJson = ReadObjectAfter(heightfieldJson, "\\"grid\\"");`,
      `        var normalizationJson = ReadObjectAfter(heightfieldJson, "\\"normalization\\"");`,
      `        var gridWidth = ReadIntAfter(gridJson, "\\"width\\"", 0);`,
      `        var gridHeight = ReadIntAfter(gridJson, "\\"height\\"", 0);`,
      `        var sampleSpacing = ReadIntAfter(gridJson, "\\"sampleSpacing\\"", 1);`,
      `        var normalizedMin = ReadIntAfter(normalizationJson, "\\"min\\"", 0);`,
      `        var normalizedMax = ReadIntAfter(normalizationJson, "\\"max\\"", 100);`,
      `        if (gridWidth <= 0 || gridHeight <= 0) ThrowImportIssue(AgmImportIssueCode.HeightfieldGridMissing, "Heightfield grid dimensions are missing.", "terrain/${baseName}.agm-heightfield.json", "positive width and height", gridWidth + "x" + gridHeight);`,
      `        if (gridWidth * gridHeight != heightfieldSampleCount) ThrowImportIssue(AgmImportIssueCode.HeightfieldSampleCountMismatch, $"Heightfield grid {gridWidth}x{gridHeight} does not match sample count {heightfieldSampleCount}.", "terrain/${baseName}.agm-heightfield.json", (gridWidth * gridHeight).ToString(), heightfieldSampleCount.ToString());`,
      "        var expectedRawBytes = heightfieldSampleCount * 2;",
      `        if (rawBytes.Length != expectedRawBytes) ThrowImportIssue(AgmImportIssueCode.Raw16ByteLengthMismatch, $"RAW16 byte length {rawBytes.Length} does not match heightfield sample count {heightfieldSampleCount}.", "${raw16Path}", expectedRawBytes.ToString(), rawBytes.Length.ToString());`,
      "        var heights = DecodeUInt16LittleEndian(rawBytes);",
      "        var raw16Min = FindMin(heights);",
      "        var raw16Max = FindMax(heights);",
      '        var resourceLayerRecordCount = CountArrayItems(resourceMapJson, "\\"tiles\\"");',
      '        var provinceLayerRecordCount = CountArrayItems(provinceMapJson, "\\"tiles\\"");',
      '        var biomeLayerRecordCount = CountArrayItems(biomeMapJson, "\\"biomes\\"");',
      '        var resourceLayerSummary = HasJsonKey(resourceMapJson, "coverageSummary") ? "coverageSummary-present" : "coverageSummary-missing";',
      '        var provinceLayerSummary = HasJsonKey(provinceMapJson, "structureSummary") ? "structureSummary-present" : "structureSummary-missing";',
      '        var biomeLayerSummary = HasJsonKey(biomeMapJson, "habitabilitySummary") ? "habitabilitySummary-present" : "habitabilitySummary-missing";',
      "",
      "        return new AgmImportedPackage",
      "        {",
      `            PackageId = "${baseName}",`,
      `            PackageName = "${packageDraft.manifest.name}",`,
      "            HeightSampleCount = heightfieldSampleCount,",
      "            GridWidth = gridWidth,",
      "            GridHeight = gridHeight,",
      "            SampleSpacing = sampleSpacing,",
      '            HeightScale = ReadStringAfter(sampleMetadataJson, "\\"heightScale\\"", "designer-defined"),',
      '            HeightSource = ReadStringAfter(manifestJson, "\\"rawEncoding\\"", "uint16-little-endian"),',
      '            ArtifactContractSchema = ReadStringAfter(packageLayoutJson, "\\"contractSchema\\"", "agm.engine-package-contract.v0"),',
      '            PackageFormat = ReadStringAfter(manifestJson, "\\"packageFormat\\"", "agm.engine-package.v0"),',
      '            LayoutVersion = ReadIntAfter(packageLayoutJson, "\\"layoutVersion\\"", 0),',
      '            ZipParsingSupported = ReadBoolAfter(packageLayoutJson, "\\"zipParsingSupported\\"", false),',
      '            ProductionPluginIncluded = ReadBoolAfter(packageLayoutJson, "\\"productionPluginIncluded\\"", false),',
      '            ValidationMode = ReadStringAfter(packageLayoutJson, "\\"validationMode\\"", "extracted-directory-only"),',
      "            NormalizedMin = normalizedMin,",
      "            NormalizedMax = normalizedMax,",
      "            RawMin = 0,",
      "            RawMax = 65535,",
      "            Raw16MinSample = raw16Min,",
      "            Raw16MaxSample = raw16Max,",
      "            Raw16Heights = heights,",
      `            ResourceLayerPath = "maps/${baseName}.agm-resource-map.json",`,
      `            ProvinceLayerPath = "maps/${baseName}.agm-province-map.json",`,
      `            BiomeLayerPath = "maps/${baseName}.agm-biome-map.json",`,
      "            ResourceLayerRecordCount = resourceLayerRecordCount,",
      "            ProvinceLayerRecordCount = provinceLayerRecordCount,",
      "            BiomeLayerRecordCount = biomeLayerRecordCount,",
      "            ResourceLayerSummary = resourceLayerSummary,",
      "            ProvinceLayerSummary = provinceLayerSummary,",
      "            BiomeLayerSummary = biomeLayerSummary,",
      '            AssetAuthoringPlanSchema = "agm.unity-asset-authoring-plan.v0",',
      '            AssetAuthoringOutputKind = ReadStringAfter(packageLayoutJson, "\\"assetAuthoringOutputKind\\"", "temporary-unity-project-editor-artifacts"),',
      '            AssetAuthoringReportBlock = "assetAuthoringPrototype",',
      "            PlannedUnityArtifactCount = 3,",
      "            CreatesUnityTerrainAsset = false,",
      "            CreatesScriptableObjectAsset = false,",
      "            CreatesPrefabAsset = false,",
      '            ExportedAssetsIncluded = ReadBoolAfter(packageLayoutJson, "\\"exportedAssetsIncluded\\"", false),',
      '            CreatesUnityTerrainAssetInExport = ReadBoolAfter(packageLayoutJson, "\\"createsUnityTerrainAssetInExport\\"", false),',
      '            CreatesScriptableObjectAssetInExport = ReadBoolAfter(packageLayoutJson, "\\"createsScriptableObjectAssetInExport\\"", false),',
      '            CreatesPrefabAssetInExport = ReadBoolAfter(packageLayoutJson, "\\"createsPrefabAssetInExport\\"", false),',
      "            CreatesUnityPackage = false,",
      "            UsesAssetDatabaseCreateAsset = false,",
      "            UsesScriptableObjectCreateInstance = false,",
      "            UsesUnityPackageManager = false,",
      "        };",
      "    }",
      "",
      "    static ushort[] DecodeUInt16LittleEndian(byte[] rawBytes)",
      "    {",
      "        // RAW16 terrain samples are stored as little-endian UInt16 values.",
      "        var values = new ushort[rawBytes.Length / 2];",
      "        for (var i = 0; i < values.Length; i++) values[i] = (ushort)(rawBytes[i * 2] | (rawBytes[i * 2 + 1] << 8));",
      "        return values;",
      "    }",
      "",
      "    static ushort FindMin(ushort[] values)",
      "    {",
      "        if (values.Length == 0) return 0;",
      "        var min = values[0];",
      "        for (var i = 1; i < values.Length; i++) if (values[i] < min) min = values[i];",
      "        return min;",
      "    }",
      "",
      "    static ushort FindMax(ushort[] values)",
      "    {",
      "        if (values.Length == 0) return 0;",
      "        var max = values[0];",
      "        for (var i = 1; i < values.Length; i++) if (values[i] > max) max = values[i];",
      "        return max;",
      "    }",
      "",
      "    static string ReadObjectAfter(string json, string marker)",
      "    {",
      "        var markerIndex = json.IndexOf(marker, StringComparison.Ordinal);",
      "        if (markerIndex < 0) return string.Empty;",
      "        var open = json.IndexOf((char)123, markerIndex);",
      "        if (open < 0) return string.Empty;",
      "        var depth = 0;",
      "        for (var i = open; i < json.Length; i++)",
      "        {",
      "            if (json[i] == (char)123) depth++;",
      "            else if (json[i] == (char)125)",
      "            {",
      "                depth--;",
      "                if (depth == 0) return json.Substring(open, i - open + 1);",
      "            }",
      "        }",
      "        return string.Empty;",
      "    }",
      "",
      "    static int ReadIntAfter(string json, string marker, int fallback)",
      "    {",
      "        var markerIndex = json.IndexOf(marker, StringComparison.Ordinal);",
      "        if (markerIndex < 0) return fallback;",
      "        var colon = json.IndexOf(':', markerIndex);",
      "        if (colon < 0) return fallback;",
      "        var start = colon + 1;",
      "        while (start < json.Length && char.IsWhiteSpace(json[start])) start++;",
      "        var end = start;",
      "        while (end < json.Length && (char.IsDigit(json[end]) || json[end] == '-')) end++;",
      "        if (end == start) return fallback;",
      "        return int.TryParse(json.Substring(start, end - start), out var value) ? value : fallback;",
      "    }",
      "",
      "    static string ReadStringAfter(string json, string marker, string fallback)",
      "    {",
      "        var markerIndex = json.IndexOf(marker, StringComparison.Ordinal);",
      "        if (markerIndex < 0) return fallback;",
      "        var colon = json.IndexOf(':', markerIndex);",
      "        if (colon < 0) return fallback;",
      "        var open = json.IndexOf('\\\"', colon + 1);",
      "        if (open < 0) return fallback;",
      "        var close = json.IndexOf('\\\"', open + 1);",
      "        if (close < 0) return fallback;",
      "        return json.Substring(open + 1, close - open - 1);",
      "    }",
      "",
      "    static int CountHeightfieldValues(string heightfieldJson)",
      "    {",
      '        return CountArrayItems(heightfieldJson, "\\"values\\"");',
      "    }",
      "",
      "    static bool ReadBoolAfter(string json, string marker, bool fallback)",
      "    {",
      "        var markerIndex = json.IndexOf(marker, StringComparison.Ordinal);",
      "        if (markerIndex < 0) return fallback;",
      "        var colon = json.IndexOf(':', markerIndex);",
      "        if (colon < 0) return fallback;",
      "        var start = colon + 1;",
      "        while (start < json.Length && char.IsWhiteSpace(json[start])) start++;",
      '        if (string.Compare(json, start, "true", 0, 4, StringComparison.OrdinalIgnoreCase) == 0) return true;',
      '        if (string.Compare(json, start, "false", 0, 5, StringComparison.OrdinalIgnoreCase) == 0) return false;',
      "        return fallback;",
      "    }",
      "",
      "    static int CountArrayItems(string json, string marker)",
      "    {",
      "        var markerIndex = json.IndexOf(marker, StringComparison.Ordinal);",
      "        if (markerIndex < 0) return 0;",
      "        var open = json.IndexOf('[', markerIndex);",
      "        if (open < 0) return 0;",
      "        var close = FindMatchingArrayClose(json, open);",
      "        if (close < 0) return 0;",
      "        var slice = json.Substring(open + 1, close - open - 1).Trim();",
      "        if (slice.Length == 0) return 0;",
      "        var depth = 0;",
      "        var count = 1;",
      "        for (var i = 0; i < slice.Length; i++)",
      "        {",
      "            var c = slice[i];",
      "            if (c == (char)123 || c == (char)91) depth++;",
      "            if (c == (char)125 || c == (char)93) depth--;",
      "            if (c == (char)44 && depth == 0) count++;",
      "        }",
      "        return count;",
      "    }",
      "",
      "    static int FindMatchingArrayClose(string json, int open)",
      "    {",
      "        var depth = 0;",
      "        for (var i = open; i < json.Length; i++)",
      "        {",
      "            if (json[i] == (char)91) depth++;",
      "            else if (json[i] == (char)93)",
      "            {",
      "                depth--;",
      "                if (depth == 0) return i;",
      "            }",
      "        }",
      "        return -1;",
      "    }",
      "",
      "    static bool HasJsonKey(string json, string key)",
      "    {",
      '        return json.IndexOf("\\"" + key + "\\"", StringComparison.Ordinal) >= 0;',
      "    }",
      "",
      "    static void ThrowImportIssue(string code, string message, string path, string expected, string actual)",
      "    {",
      "        throw new AgmImportException(new AgmImportIssue",
      "        {",
      "            Code = code,",
      "            Message = message,",
      "            Path = path,",
      "            Expected = expected,",
      "            Actual = actual,",
      "        });",
      "    }",
      "}",
    ].join("\n"),
  };
}
