import type {
  ImporterStubContext,
  ImporterStubFile,
} from "./worldDocumentImporterStubTypes";

export function createGodotImporterStubFiles({
  manifestPath,
  sampleMetadataPath,
  heightfieldPath,
  raw16Path,
}: ImporterStubContext): ImporterStubFile[] {
  return [
    {
      path: "handoff/importers/godot/README.md",
      content: [
        "# Godot AGM importer source sample",
        "",
        "This folder contains a source sample for adapting an AGM Engine Package into a Godot tool script or importer.",
        "It is not a production plugin, Godot addon, or supported runtime integration.",
        "Copy agm_importer_stub.gd.txt into an editor plugin or tool script and rename it to .gd when adapting it.",
        "Production addon review target: addons/agm_importers_godot, but plugin.cfg and production .gd files are intentionally not bundled in this Engine Package ZIP.",
        "The source sample reads manifest JSON, importer sample metadata, heightfield JSON, RAW16 little-endian height samples, and resource/province/biome map layer record counts.",
        "Godot Resource output, PackedScene output, plugin.cfg, production .gd files, and EditorImportPlugin registration remain release-candidate work outside this Engine Package ZIP.",
        `Read ${sampleMetadataPath} for the terrain and map layer paths, then adapt paths and Godot data types manually.`,
        "",
        "中文：此目录包含用于将 AGM Engine Package 接入 Godot 工具脚本或导入器的源码示例。",
        "它不是生产级插件、Godot addon 或已支持的运行时集成。",
        "请按项目需要手动适配路径、Godot 数据类型和导入流程。",
      ].join("\n"),
    },
    {
      path: "handoff/importers/godot/agm_importer_stub.gd.txt",
      content: [
        "@tool",
        "extends RefCounted",
        "",
        'const AGM_IMPORTER_CONTRACT := "agm.godot-importer-source-sample.v0"',
        "const PRODUCTION_ADDON_INCLUDED := false",
        "const CREATES_GODOT_RESOURCES := false",
        "const CREATES_PACKED_SCENES := false",
        "",
        "func import_agm_package(package_root: String) -> Dictionary:",
        `\tvar manifest := _read_json(package_root.path_join("${manifestPath}"))`,
        `\tvar sample_metadata := _read_json(package_root.path_join("${sampleMetadataPath}"))`,
        `\tvar heightfield := _read_json(package_root.path_join("${heightfieldPath}"))`,
        `\tvar raw_file := FileAccess.open(package_root.path_join("${raw16Path}"), FileAccess.READ)`,
        "\tvar raw_bytes := raw_file.get_buffer(raw_file.get_length()) if raw_file else PackedByteArray()",
        "\tvar raw16_samples := _decode_raw16_little_endian(raw_bytes)",
        '\tvar height_values := heightfield.get("values", [])',
        "\tif raw16_samples.size() != height_values.size():",
        '\t\tpush_error("AGM RAW16 sample count mismatch: %d != %d" % [raw16_samples.size(), height_values.size()])',
        '\tvar map_layers := sample_metadata.get("mapLayers", {})',
        '\tvar resource_map := _read_json(package_root.path_join(map_layers.get("resource", "")))',
        '\tvar province_map := _read_json(package_root.path_join(map_layers.get("province", "")))',
        '\tvar biome_map := _read_json(package_root.path_join(map_layers.get("biome", "")))',
        "\tvar summary := {",
        '\t\t"package_id": manifest.get("manifest", {}).get("id", ""),',
        '\t\t"height_sample_count": height_values.size(),',
        '\t\t"raw16_sample_count": raw16_samples.size(),',
        '\t\t"resource_records": resource_map.get("tiles", []).size(),',
        '\t\t"province_records": province_map.get("tiles", []).size(),',
        '\t\t"biome_records": biome_map.get("biomes", []).size(),',
        '\t\t"production_addon_included": PRODUCTION_ADDON_INCLUDED,',
        '\t\t"creates_godot_resources": CREATES_GODOT_RESOURCES,',
        '\t\t"creates_packed_scenes": CREATES_PACKED_SCENES,',
        "\t}",
        '\tprint("AGM Godot source sample: %s height samples, %s RAW16 samples" % [summary.height_sample_count, summary.raw16_sample_count])',
        "\treturn summary",
        "",
        "func _read_json(path: String) -> Dictionary:",
        "\tvar text := FileAccess.get_file_as_string(path)",
        "\tvar parsed := JSON.parse_string(text)",
        "\treturn parsed if parsed is Dictionary else {}",
        "",
        "func _decode_raw16_little_endian(bytes: PackedByteArray) -> Array[int]:",
        "\tvar samples: Array[int] = []",
        "\tfor index in range(0, bytes.size() - 1, 2):",
        "\t\tsamples.append(bytes[index] | (bytes[index + 1] << 8))",
        "\treturn samples",
      ].join("\n"),
    },
  ];
}
