export function createEngineValidationPlans() {
  const unityValidationHarness = {
    status: "available",
    mode: "local-structure-validation-with-optional-unity-cli",
    scriptPath: "scripts/validate-unity-export.mjs",
    defaultValidation: "structure-only",
    unityCliValidation: "optional-batchmode-terrain-prototype-check",
    batchmodeMethod: "AgmValidationBatchmode.Run",
    importerSmokeTest: "AgmRuntimePackageImporter.ImportFromUnpackedPackage",
    prototypeReport: "Assets/AGM/Validation/agm-imported-package-report.json",
    terrainPrototypeReport: "terrainPrototype",
    prototypeValidation: "metadata-json-only",
    reportSchema: "agm.unity-validation-report.v0",
    runtimeValidated: false,
    editorValidated: false,
    createsUnityProject: false,
    checks: [
      "manifest-json",
      "importer-sample-metadata",
      "artifact-contract",
      "layout-version",
      "layout-required-files",
      "sample-metadata-contract",
      "unity-artifact-paths",
      "package-layout",
      "unity-layout-contract",
      "engine-stub-contracts",
      "production-plugin-boundary",
      "unity-production-importer-packaging-plan",
      "unity-production-importer-package-scaffold",
      "unity-production-importer-runtime-contract",
      "unity-package-compile-gate",
      "unity-package-import-smoke-test",
      "no-production-plugin-claims",
      "zip-validation-disabled",
      "raw16-byte-length",
      "raw16-little-endian-decode-sample",
      "map-layer-json",
      "terrain-prototype-grid",
      "terrain-prototype-height-source",
      "terrain-prototype-raw16-range",
      "terrain-prototype-map-layer-refs",
      "unity-contract-consumed",
      "unity-package-layout-consumed",
      "unity-map-layer-records",
      "unity-map-layer-summaries",
      "unity-prototype-report-contract",
      "unity-prototype-non-asset-output",
      "unity-asset-authoring-spike-metadata",
      "unity-asset-authoring-report",
      "unity-asset-authoring-non-asset-output",
      "unity-forbidden-editor-apis-absent",
      "unity-cli-executable",
      "unity-project-created",
      "unity-source-copied",
      "unity-editor-compile",
      "unity-runtime-importer-called",
      "unity-imported-package-report",
      "unity-data-asset-prototype",
    ],
  };
  const unityVerticalSlicePrototype = {
    status: "source-sample-prototype",
    scope: [
      "artifact-contract",
      "package-layout",
      "terrain-raw16",
      "heightfield-grid",
      "resource-map-layer",
      "province-map-layer",
      "biome-map-layer",
      "prototype-json-report",
    ],
    outputKind: "metadata-json-only",
    outputReport: "Assets/AGM/Validation/agm-imported-package-report.json",
    layerReport: "mapLayerPrototype",
    terrainReport: "terrainPrototype",
    artifactContractReport: "artifactContractPrototype",
    productionPluginIncluded: false,
    createsUnityTerrainAsset: false,
    createsScriptableObjectAsset: false,
    runtimeValidated: false,
    editorValidated: false,
  };
  const realEngineSmokeRecords = {
    schema: "agm.real-engine-smoke-records.v0",
    status: "not-captured",
    releaseCandidateReady: false,
    records: {
      unity: {
        engine: "unity",
        status: "not-captured",
        requiredForReleaseCandidate: true,
        executableValidated: false,
        smokeType: "batchmode-package-import-and-editor-prototype",
        expectedCommand:
          "npm run validate:unity-export -- --dir <extracted-package-root> --unity <Unity executable> --json",
        reportSchema: "agm.unity-validation-report.v0",
        mockOrFixtureResult: false,
      },
      godot: {
        engine: "godot",
        status: "not-captured",
        requiredForReleaseCandidate: true,
        executableValidated: false,
        smokeType: "addon-import-contract-smoke",
        expectedDeliverableRoot: "addons/agm_importers_godot",
        reportSchema: "agm.godot-addon-smoke-report.v0",
        mockOrFixtureResult: false,
      },
      unreal: {
        engine: "unreal",
        status: "not-captured",
        requiredForReleaseCandidate: true,
        executableValidated: false,
        smokeType: "plugin-commandlet-import-contract-smoke",
        expectedDeliverableRoot: "Plugins/AGMImportersUnreal",
        reportSchema: "agm.unreal-plugin-smoke-report.v0",
        mockOrFixtureResult: false,
      },
    },
    capturedEngines: [],
    missingEngines: ["unity", "godot", "unreal"],
    nextAction: "capture-real-engine-smoke-records",
  };
  const unityAssetAuthoringSpike = {
    status: "editor-source-sample-prototype",
    schema: "agm.unity-asset-authoring-plan.v0",
    sourceScript:
      "handoff/importers/unity/Editor/AgmAssetAuthoringPrototype.cs.txt",
    outputKind: "temporary-unity-project-editor-artifacts",
    outputScope: "validator-temp-unity-project-only",
    reportBlock: "assetAuthoringPrototype",
    intendedArtifacts: [
      {
        kind: "terrain-data",
        futureUnityType: "TerrainData",
        exportedAssetIncluded: false,
        validatorTempProjectCreatesAsset: true,
      },
      {
        kind: "world-scriptable-object",
        futureUnityType: "ScriptableObject",
        exportedAssetIncluded: false,
        validatorTempProjectCreatesAsset: true,
      },
      {
        kind: "prefab",
        futureUnityType: "Prefab",
        exportedAssetIncluded: false,
        validatorTempProjectCreatesAsset: true,
      },
    ],
    allowedOnlyInSourceScript: [
      "AssetDatabase.CreateAsset",
      "ScriptableObject.CreateInstance",
      "PrefabUtility.SaveAsPrefabAsset",
    ],
    forbiddenProductionApis: [
      "UnityEditor.PackageManager",
      "AssetDatabase.ExportPackage",
    ],
    exportedAssetsIncluded: false,
    createsUnityTerrainAssetInExport: false,
    createsScriptableObjectAssetInExport: false,
    createsPrefabAssetInExport: false,
    createsUnityTerrainAsset: false,
    createsScriptableObjectAsset: false,
    createsPrefabAsset: false,
    createsUnityPackage: false,
    productionPluginIncluded: false,
    runtimeValidated: false,
    editorValidated: false,
  };

  return {
    unityValidationHarness,
    unityVerticalSlicePrototype,
    realEngineSmokeRecords,
    unityAssetAuthoringSpike,
  };
}

export type EngineValidationPlans = ReturnType<
  typeof createEngineValidationPlans
>;
