export function createUnrealProductionImporterPackagingPlan() {
  return {
    status: "source-sample-scaffolded-separate-plugin-review-required",
    scaffoldStatus: "runtime-importer-source-sample-contract",
    pluginName: "AGMImportersUnreal",
    pluginRoot: "Plugins/AGMImportersUnreal",
    distribution: "separate-versioned-unreal-plugin",
    targetUnrealVersion: "5.x",
    includedInEnginePackageZip: false,
    requiresProductionizationReview: true,
    upluginIncludedInEnginePackage: false,
    cppSourceIncludedAsProductionPlugin: false,
    productionPluginIncluded: false,
    plannedFiles: [
      "AGMImportersUnreal.uplugin",
      "Source/AGMImportersUnreal/AGMImportersUnreal.Build.cs",
      "Source/AGMImportersUnreal/Private/AgmImporter.cpp",
      "README.md",
    ],
    sourceSampleInputs: [
      "handoff/importers/unreal/README.md",
      "handoff/importers/unreal/AgmImporterStub.cpp.txt",
    ],
    runtimeImporterContract: {
      status: "reads-engine-package-contract-source-sample",
      readsManifest: true,
      readsSampleMetadata: true,
      readsHeightfieldJson: true,
      readsRaw16Terrain: true,
      decodesRaw16LittleEndian: true,
      countsMapLayerRecords: true,
      productionAssetOutput: false,
      createsUnrealAssets: false,
      createsUObjects: false,
      createsImportFactory: false,
    },
    validationGates: [
      "unreal-source-sample-present",
      "unreal-production-plugin-boundary",
      "no-export-zip-plugin-contamination",
    ],
    releaseCandidateReview: {
      status: "pre-plugin-release-candidate-checklist",
      sourceSampleDocumented: true,
      pluginBoundaryDocumented: true,
      realUnrealValidationRequired: true,
      releaseCandidateReady: false,
    },
    pluginBoundaryReview: {
      schema: "agm.unreal-plugin-boundary-review.v0",
      status: "source-sample-boundary-verified",
      deliverableRoot: "Plugins/AGMImportersUnreal",
      enginePackageZipIncludesDeliverable: false,
      productionPluginIncluded: false,
      upluginIncludedInEnginePackage: false,
      buildCsIncludedInEnginePackage: false,
      productionCppIncludedInEnginePackage: false,
      cookedAssetsIncludedInEnginePackage: false,
      sourceSampleOnly: true,
      realUnrealSmokeRequired: true,
      releaseCandidateReady: false,
    },
    enginePackageBoundaryRef: "productionPluginBoundary",
  };
}
