export function createGodotProductionImporterPackagingPlan() {
  return {
    status: "source-sample-scaffolded-separate-addon-review-required",
    scaffoldStatus: "runtime-importer-source-sample-contract",
    addonName: "agm_importers_godot",
    addonRoot: "addons/agm_importers_godot",
    distribution: "separate-versioned-godot-addon",
    targetGodotVersion: "4.x",
    includedInEnginePackageZip: false,
    requiresProductionizationReview: true,
    pluginCfgIncludedInEnginePackage: false,
    gdScriptIncludedAsProductionAddon: false,
    productionAddonIncluded: false,
    plannedFiles: ["plugin.cfg", "agm_importer.gd", "README.md"],
    sourceSampleInputs: [
      "handoff/importers/godot/README.md",
      "handoff/importers/godot/agm_importer_stub.gd.txt",
    ],
    runtimeImporterContract: {
      status: "reads-engine-package-contract-source-sample",
      readsManifest: true,
      readsSampleMetadata: true,
      readsHeightfieldJson: true,
      readsRaw16Terrain: true,
      decodesRaw16LittleEndian: true,
      countsMapLayerRecords: true,
      productionAssetOutput: false,
      createsGodotResources: false,
      createsPackedScenes: false,
      createsImportPlugin: false,
    },
    validationGates: [
      "godot-source-sample-present",
      "godot-production-addon-boundary",
      "no-export-zip-plugin-contamination",
    ],
    releaseCandidateReview: {
      status: "pre-addon-release-candidate-checklist",
      sourceSampleDocumented: true,
      addonBoundaryDocumented: true,
      realGodotValidationRequired: true,
      releaseCandidateReady: false,
    },
    addonBoundaryReview: {
      schema: "agm.godot-addon-boundary-review.v0",
      status: "source-sample-boundary-verified",
      deliverableRoot: "addons/agm_importers_godot",
      enginePackageZipIncludesDeliverable: false,
      productionAddonIncluded: false,
      pluginCfgIncludedInEnginePackage: false,
      productionGdScriptsIncludedInEnginePackage: false,
      resourceOutputsIncludedInEnginePackage: false,
      sceneOutputsIncludedInEnginePackage: false,
      sourceSampleOnly: true,
      realGodotSmokeRequired: true,
      releaseCandidateReady: false,
    },
    enginePackageBoundaryRef: "productionPluginBoundary",
  };
}
