import type { ImporterStubFile } from "./worldDocumentImporterStubTypes";

export function createUnityRuntimePackageTypesFile(): ImporterStubFile {
  return {
    path: "handoff/importers/unity/Runtime/AgmPackageTypes.cs.txt",
    content: [
      "using System;",
      "using System.Collections.Generic;",
      "",
      "public sealed class AgmImportedPackage",
      "{",
      "    public string PackageId;",
      "    public string PackageName;",
      "    public int HeightSampleCount;",
      "    public int GridWidth;",
      "    public int GridHeight;",
      "    public int SampleSpacing;",
      "    public string HeightScale;",
      "    public string HeightSource;",
      "    public string ArtifactContractSchema;",
      "    public string PackageFormat;",
      "    public int LayoutVersion;",
      "    public bool ZipParsingSupported;",
      "    public bool ProductionPluginIncluded;",
      "    public string ValidationMode;",
      "    public int NormalizedMin;",
      "    public int NormalizedMax;",
      "    public int RawMin;",
      "    public int RawMax;",
      "    public ushort Raw16MinSample;",
      "    public ushort Raw16MaxSample;",
      "    public ushort[] Raw16Heights;",
      "    public string ResourceLayerPath;",
      "    public string ProvinceLayerPath;",
      "    public string BiomeLayerPath;",
      "    public int ResourceLayerRecordCount;",
      "    public int ProvinceLayerRecordCount;",
      "    public int BiomeLayerRecordCount;",
      "    public string ResourceLayerSummary;",
      "    public string ProvinceLayerSummary;",
      "    public string BiomeLayerSummary;",
      "    public string AssetAuthoringPlanSchema;",
      "    public string AssetAuthoringOutputKind;",
      "    public string AssetAuthoringReportBlock;",
      "    public int PlannedUnityArtifactCount;",
      "    public bool CreatesUnityTerrainAsset;",
      "    public bool CreatesScriptableObjectAsset;",
      "    public bool CreatesPrefabAsset;",
      "    public bool ExportedAssetsIncluded;",
      "    public bool CreatesUnityTerrainAssetInExport;",
      "    public bool CreatesScriptableObjectAssetInExport;",
      "    public bool CreatesPrefabAssetInExport;",
      "    public bool CreatesUnityPackage;",
      "    public bool UsesAssetDatabaseCreateAsset;",
      "    public bool UsesScriptableObjectCreateInstance;",
      "    public bool UsesUnityPackageManager;",
      "    public readonly List<string> Warnings = new List<string>();",
      "}",
      "",
      "public static class AgmImportIssueCode",
      "{",
      '    public const string PackageRootMissing = "package-root-missing";',
      '    public const string RequiredDirectoryMissing = "required-directory-missing";',
      '    public const string RequiredFileCountMismatch = "required-file-count-mismatch";',
      '    public const string HeightfieldGridMissing = "heightfield-grid-missing";',
      '    public const string HeightfieldSampleCountMismatch = "heightfield-sample-count-mismatch";',
      '    public const string Raw16ByteLengthMismatch = "raw16-byte-length-mismatch";',
      "}",
      "",
      "public sealed class AgmImportIssue",
      "{",
      '    public string Schema = "agm.unity-runtime-import-issue.v0";',
      "    public string Code;",
      "    public string Message;",
      "    public string Path;",
      "    public string Expected;",
      "    public string Actual;",
      "}",
      "",
      "public sealed class AgmImportException : Exception",
      "{",
      '    public AgmImportException(AgmImportIssue issue) : base(issue == null ? "AGM import failed." : issue.Message)',
      "    {",
      '        Issue = issue ?? new AgmImportIssue { Code = "unknown", Message = "AGM import failed." };',
      "    }",
      "",
      "    public AgmImportIssue Issue { get; private set; }",
      "}",
      "",
      "public sealed class AgmImportReport",
      "{",
      "    public int Raw16ByteLength;",
      "    public int ExpectedRaw16ByteLength;",
      "    public bool Raw16LengthMatchesHeightfield;",
      "    public string ManifestSummary;",
      "}",
    ].join("\n"),
  };
}
