import type {
  ImporterStubContext,
  ImporterStubFile,
} from "./worldDocumentImporterStubTypes";

export function createUnrealImporterStubFiles({
  manifestPath,
  sampleMetadataPath,
  heightfieldPath,
  raw16Path,
}: ImporterStubContext): ImporterStubFile[] {
  return [
    {
      path: "handoff/importers/unreal/README.md",
      content: [
        "# Unreal AGM importer source sample",
        "",
        "This folder contains a source sample for adapting an AGM Engine Package into an Unreal Editor Utility, commandlet, or import factory.",
        "It is not a production plugin, Unreal package, or supported runtime integration.",
        "Use AgmImporterStub.cpp.txt as an Editor Utility, commandlet, or custom import factory starting point.",
        "Production plugin review target: Plugins/AGMImportersUnreal, but .uplugin, Build.cs, production .cpp/.h files, and cooked Unreal assets are intentionally not bundled in this Engine Package ZIP.",
        "The source sample reads manifest JSON, importer sample metadata, heightfield JSON, RAW16 little-endian height samples, and resource/province/biome map layer record counts.",
        "Unreal asset output, UObject authoring, ImportFactory registration, .uasset output, and production plugin packaging remain release-candidate work outside this Engine Package ZIP.",
        `Read ${manifestPath}, then import ${raw16Path} using uint16 little-endian terrain settings and adapt Unreal data types manually.`,
        "",
        "中文：此目录包含用于将 AGM Engine Package 接入 Unreal Editor Utility、commandlet 或自定义导入工厂的源码示例。",
        "它不是生产级插件、Unreal package 或已支持的运行时集成。",
        "请按项目需要手动适配路径、Unreal 数据类型和导入流程。",
      ].join("\n"),
    },
    {
      path: "handoff/importers/unreal/AgmImporterStub.cpp.txt",
      content: [
        '#include "Misc/FileHelper.h"',
        '#include "Misc/Paths.h"',
        "",
        "void ImportAgmPackageStub(const FString& PackageRoot)",
        "{",
        "struct FAgmImporterSummary",
        "{",
        "    FString PackageId;",
        "    int32 HeightSampleCount = 0;",
        "    int32 Raw16SampleCount = 0;",
        "    int32 ResourceRecords = 0;",
        "    int32 ProvinceRecords = 0;",
        "    int32 BiomeRecords = 0;",
        "    bool bProductionPluginIncluded = false;",
        "    bool bCreatesUnrealAssets = false;",
        "};",
        "",
        "FAgmImporterSummary ImportAgmPackageStub(const FString& PackageRoot)",
        "{",
        `    const FString ManifestPath = FPaths::Combine(PackageRoot, TEXT("${manifestPath}"));`,
        `    const FString SampleMetadataPath = FPaths::Combine(PackageRoot, TEXT("${sampleMetadataPath}"));`,
        `    const FString HeightfieldPath = FPaths::Combine(PackageRoot, TEXT("${heightfieldPath}"));`,
        `    const FString Raw16Path = FPaths::Combine(PackageRoot, TEXT("${raw16Path}"));`,
        "    FString ManifestJson;",
        "    FString SampleMetadataJson;",
        "    FString HeightfieldJson;",
        "    TArray<uint8> Raw16Bytes;",
        "    FFileHelper::LoadFileToString(ManifestJson, *ManifestPath);",
        "    FFileHelper::LoadFileToString(SampleMetadataJson, *SampleMetadataPath);",
        "    FFileHelper::LoadFileToString(HeightfieldJson, *HeightfieldPath);",
        "    FFileHelper::LoadFileToArray(Raw16Bytes, *Raw16Path);",
        "    const TArray<uint16> Raw16Samples = DecodeRaw16LittleEndian(Raw16Bytes);",
        '    const int32 HeightSampleCount = CountJsonArrayItems(HeightfieldJson, TEXT("values"));',
        "    if (Raw16Samples.Num() != HeightSampleCount)",
        "    {",
        '        UE_LOG(LogTemp, Error, TEXT("AGM RAW16 sample count mismatch: %d != %d"), Raw16Samples.Num(), HeightSampleCount);',
        "    }",
        "    FAgmImporterSummary Summary;",
        '    Summary.PackageId = ReadJsonStringField(ManifestJson, TEXT("id"));',
        "    Summary.HeightSampleCount = HeightSampleCount;",
        "    Summary.Raw16SampleCount = Raw16Samples.Num();",
        '    Summary.ResourceRecords = CountJsonArrayItems(ReadJsonFileFromMetadata(PackageRoot, SampleMetadataJson, TEXT("resource")), TEXT("tiles"));',
        '    Summary.ProvinceRecords = CountJsonArrayItems(ReadJsonFileFromMetadata(PackageRoot, SampleMetadataJson, TEXT("province")), TEXT("tiles"));',
        '    Summary.BiomeRecords = CountJsonArrayItems(ReadJsonFileFromMetadata(PackageRoot, SampleMetadataJson, TEXT("biome")), TEXT("biomes"));',
        "    return Summary;",
        "}",
        "",
        "TArray<uint16> DecodeRaw16LittleEndian(const TArray<uint8>& Bytes)",
        "{",
        "    TArray<uint16> Samples;",
        "    for (int32 Index = 0; Index + 1 < Bytes.Num(); Index += 2)",
        "    {",
        "        Samples.Add(static_cast<uint16>(Bytes[Index] | (Bytes[Index + 1] << 8)));",
        "    }",
        "    return Samples;",
        "}",
        "",
        "int32 CountJsonArrayItems(const FString& Json, const TCHAR* FieldName)",
        "{",
        "    return 0; // Replace with FJsonSerializer parsing when promoting this sample into a plugin.",
        "}",
        "",
        "FString ReadJsonStringField(const FString& Json, const TCHAR* FieldName)",
        "{",
        "    return FString();",
        "}",
        "",
        "FString ReadJsonFileFromMetadata(const FString& PackageRoot, const FString& SampleMetadataJson, const TCHAR* LayerName)",
        "{",
        "    return FString();",
        "}",
      ].join("\n"),
    },
  ];
}
